version: "2"
services:
  sw52_shop:
    container_name: sw52_shop
    image: mittwald/shopware:latest
    #restart: always
    links:
      - sw52_db:db
      - sw52_mailcatcher:smtp
    volumes:
      - ./Volumes/Shop/Config/php/php.ini:/usr/local/etc/php/php.ini
      - data-sync-sw52:/var/www/html:rw
    environment:
      VIRTUAL_HOST: www.sw52.dev

  sw52_db:
    container_name: sw52_db
    image: mysql:5.7
    #restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: swuser
      MYSQL_PASSWORD: swpassword
    volumes:
      - ./Volumes/Db/:/var/lib/mysql

  sw52_nginx_proxy:
    container_name: sw52_nginx_proxy
    #restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - 8080:80
      - 8043:443
      - 8088:1080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  sw52_phpmyadmin:
    container_name: sw52_phpmyadmin
    #restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - sw52_db:db
    environment:
      VIRTUAL_HOST: db.sw52.dev

  sw52_mailcatcher:
    image: hinshun/mailcatcher
    environment:
      VIRTUAL_HOST: mail.sw52.dev
    ports:
      - 1080:1080 

volumes:
  data-sync-sw52:
    external: true

