version: "2"
services:
  sw53_shop:
    container_name: sw53_shop
    build: ./Docker/php7
    #restart: always
    links:
      - sw53_db:db
      - sw53_mailcatcher:smtp
    volumes:
      - ./Volumes/Shop/Config/php/php.ini:/usr/local/etc/php/php.ini
      - data-sync-sw53:/var/www/html:rw
    environment:
      VIRTUAL_HOST: www.sw53.dev

  sw53_db:
    container_name: sw53_db
    image: mysql:5.7
    #restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: swuser
      MYSQL_PASSWORD: swpassword
    volumes:
      - ./Volumes/Db/:/var/lib/mysql

  sw53_nginx_proxy:
    container_name: sw53_nginx_proxy
    #restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - 8080:80
      - 8043:443
      - 8088:1080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  sw53_phpmyadmin:
    container_name: sw53_phpmyadmin
    #restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - sw53_db:db
    environment:
      VIRTUAL_HOST: db.sw53.dev

  sw53_mailcatcher:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: mail.sw53.dev
    ports:
      - 3309:1080 

volumes:
  data-sync-sw53:
    external: true

